from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer

chatbot = ChatBot("Chatbot")

training = ListTrainer(chatbot)
simple_training_data = [
    "Hello, how are you?",
    "What's your name?",
    "How old are you?",
    "Tell me a joke.",
    "What is the meaning of life?",
    "What's your favorite color?",
    "Do you like pizza?",
    "Tell me about yourself.",
    "What are your hobbies?",
    "Can you sing?",
    "What's the weather like today?",
    "What is your favorite movie?",
    "How do I get to the nearest coffee shop?",
    "Tell me a fun fact.",
    "Do you have any pets?",
    "What's the capital of France?",
    "What's your favorite book?",
    "Who is your favorite actor?",
    "What's the best restaurant in town?",
    "How do I cook pasta?",
    "Can you help me with my homework?",
    "Tell me a story.",
    "What's your favorite song?",
    "Where do you live?",
    "What's the latest news?",
    "What's the time?",
    "Tell me a riddle.",
    "Do you believe in aliens?",
    "What's the tallest building in the world?",
    "What's your favorite sport?",
    "What's the population of London?",
    "How do I tie a tie?",
    "What's the distance between New York and Los Angeles?",
    "What's the square root of 144?",
    "Tell me about the history of computers.",
    "What's the longest river in the world?",
    "What's your favorite food?",
    "Do you play any musical instruments?",
    "How do I say 'hello' in French?",
    "What's the largest country in Africa?",
    "Tell me a random fact.",
    "What's the capital of Australia?",
    "What's the temperature in Tokyo?",
    "How do I change a flat tire?",
    "What's the currency of Brazil?",
    "Do you have any siblings?",
    "What's the largest ocean?",
    "What's the highest mountain in the world?",
    "Tell me a famous quote.",
    "What's your favorite TV show?",
    "Where were you born?",
    "What's your favorite holiday?",
    "Do you like ice cream?",
    "What's the deepest part of the ocean?",
    "What's the national flower of Japan?",
    "How do I make a paper airplane?",
    "What's the speed of light?",
    "Tell me about your family.",
    "What's the largest desert in the world?",
    "What's your favorite season?",
    "What's the capital of China?",
    "What's the population of India?",
    "Tell me about a dream you had.",
    "What's the largest planet in our solar system?",
    "What's the distance between Earth and the Moon?",
    "How do I take a screenshot?",
    "What's the currency of Japan?",
    "Do you believe in ghosts?",
    "What's the national animal of Canada?",
    "Tell me a tongue twister.",
    "What's your favorite type of music?",
    "What's the longest bridge in the world?",
    "What's the height of the Eiffel Tower?",
    "How do I make a chocolate cake?",
    "What's the capital of Russia?",
    "What's the population of the United States?",
    "Tell me about your favorite hobby.",
    "What's the average rainfall in London?",
    "What's your favorite animal?",
    "Do you like to dance?",
    "What's the shortest day of the year?",
    "What's the national bird of Australia?",
    "How do I create a new folder on my computer?",
    "What's the currency of France?",
    "Do you have any favorite quotes?",
    "What's the national sport of Canada?",
    "Tell me a knock-knock joke.",
    "What's your favorite board game?",
    "Where is the Great Wall of China located?",
    "What's the population of Japan?",
    "What's the average lifespan of a cat?",
    "How do I make a cup of tea?",
    "What's the capital of Germany?",
    "What's the tallest tree in the world?",
    "Tell me about your favorite vacation.",
    "What's the fastest land animal?",
    "What's the national flower of England?",
    "Do you have any favorite movies?",
    "What's the national dish of Italy?",
    "How do I reset my password?",
    "What's the currency of the United Kingdom?",
    "What's the national bird of the United States?",
    "Tell me about your dream job.",
    "What's the largest waterfall in the world?",
    "What's the deepest lake in the world?",
    "What's your favorite subject in school?",
    "How do I take a screenshot on my phone?",
    "What's the national animal of India?",
    "What's the national sport of India?",
    "Tell me a fun fact about space.",
    "What's your favorite type of cuisine?",
    "Where is the Statue of Liberty located?",
    "What's the population of China?",
    "What's the capital of Brazil?",
    "How do I make a paper boat?",
    "What's the national flower of France?",
    "What's the highest waterfall in the world?",
    "Tell me about your favorite book.",
    "What's the average temperature in London?",
    "What's your favorite movie genre?",
    "Do you like to travel?",
    "What's the national dish of Japan?",
    "How do I change my profile picture?",
    "What's the currency of Germany?",
    "What's the national bird of France?",
    "Tell me a fun fact about animals.",
    "What's your favorite type of dessert?",
    "Where is the Taj Mahal located?",
    "What's the population of Australia?",
    "What's the capital of Canada?",
    "How do I send a text message?",
    "What's the national animal of France?",
    "What's the national sport of Australia?",
    "Tell me a fun fact about technology.",
    "What's your favorite genre of music?",
    "Where is the Colosseum located?",
    "What's the population of Germany?",
    "What's the capital of Italy?",
    "How do I create a new email account?",
    "What's the currency of Australia?",
    "What's the national bird of Germany?",
    "Tell me a fun fact about the human body."
]
training.train(simple_training_data)
while True:
    query = input("> ")
    if query in "exit":
        break
    else:
        print(chatbot.get_response(query))

